export enum SystemMetricType {
  PHYSICAL_CAPACITY = 'Physical capacity',
  PHYSICAL_SUBS = 'Physical subs',
  AVAILABLE_CAPACITY = 'Available capacity',
  LOGICAL_USAGE = 'Logical used',
  PHYSICAL_USAGE = 'Physical used',
  COMPRESS_RATIO = 'Compression ratio',
  WORKLOAD = 'workload',
  RESPONSE = 'response',
  TRANSFER = 'transfer',
  HDD = 'hdd',
  CPU = 'cpu',
  WRITE_PENDING = 'write_pending',
  SLA_EVENTS = 'sla_events',
  OUT_OF_SLA_TIME = 'out_of_sla_time',
  DISBALANCE_EVENTS = 'disbalance_events',
  PREDICTION_L1 = 'Prediction_L1',
  PREDICTION_L2 = 'Prediction_L2',
  PREDICTION_L3 = 'Prediction_L3',
  INFO = 'info',
}
